# Generated by Django 5.1.1 on 2024-10-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0018_auto_20211028_1634"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livros",
            name="emprestado",
        ),
        migrations.DeleteModel(
            name="Emprestimos",
        ),
    ]
