# Generated by Django 5.1.2 on 2024-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0019_remove_livros_emprestado_delete_emprestimos"),
    ]

    operations = [
        migrations.AddField(
            model_name="livros",
            name="descricao",
            field=models.CharField(default="descricao do livro", max_length=200),
            preserve_default=False,
        ),
    ]
